"""AI Video Check — MCP server.

A thin layer over the public API (/v1). It has no keys, accounts, credits or
detection logic of its own, and must never grow any: identity comes from the
caller's API key, money from the same credits as the website, answers from
/v1. API documentation: https://www.aivideocheck.net/en/developers

Two ways to run it:

  remote (Streamable HTTP, behind nginx at https://api.aivideocheck.net/mcp)
      uvicorn avc_mcp:app --host 127.0.0.1 --port 8100
      The client sends its own key: `Authorization: Bearer avc_live_…`.
      The server's environment never supplies a key in this mode — otherwise
      every anonymous caller would spend one account's credits.

  local (stdio, for Claude Code, Cursor and similar)
      AVC_API_KEY=avc_live_… python avc_mcp.py
      Adds `check_file`, which uploads a video from the user's own disk: a
      remote server cannot see those files, a local one can.

What the assistant is told matters as much as the number. It retells our
answer in its own words and can turn "72%" into "definitely AI", so the
caveats travel inside every result, not only in documentation. The picture
and sound scores are always given separately: on the face-swap test of
28.09 the picture scored 5% and the sound 75%, and an assistant that sees
both can say "the voice looks synthetic" instead of repeating a low total.
"""
from __future__ import annotations

import asyncio
import os
import uuid
from pathlib import Path
from typing import Any, Optional

import httpx
from mcp.server.mcpserver import Context, MCPServer
from mcp.server.mcpserver.exceptions import ToolError
from mcp.server.transport_security import TransportSecuritySettings
from mcp_types import ToolAnnotations

API_BASE = os.getenv("AVC_API_BASE", "https://api.aivideocheck.net").rstrip("/")
# How long check_video waits for a result before handing back the id. Most
# checks take 10-30 s; nginx in front allows 120 s per request.
WAIT_S = float(os.getenv("AVC_MCP_WAIT_S", "55"))
POLL_S = 2.0
MAX_FILE_MB = 500
SITE = "https://www.aivideocheck.net"
USER_AGENT = "aivideocheck-mcp/1.0"
# On our server, MCP talks to the API backend over loopback (AVC_API_BASE)
# and passes on the caller's address that nginx put in X-Real-IP. Without it /v1
# would see every MCP user as one IP, and its per-IP limit on failed keys would
# let one client with a wrong key lock everyone else out for a minute. The
# backend trusts X-Real-IP only from a loopback peer, and
# this server listens on 127.0.0.1 behind nginx, which overwrites the header.
FORWARD_CLIENT_IP = os.getenv("AVC_MCP_FORWARD_CLIENT_IP") == "1"

# Set once at start-up. Only stdio may read a key from the environment.
_MODE = {"stdio": False}

VERDICT = {
    "real": "No AI signals",
    "likely_real": "Few AI signals",
    "likely_ai": "AI signals detected",
    "ai": "AI-generated",
}

HOW_TO_READ = (
    "How to read this: it is a probability from automated models, not proof. "
    "A high score is strong evidence of AI generation. A low score means no signs "
    "of generation were found, not that the video is authentic or shows what its "
    "caption claims. Editing, visual effects and a face swapped onto real footage "
    "are not detected. If the picture and sound scores disagree, say so: the "
    "disagreement is often the most useful part of the answer."
)

server = MCPServer(
    name="AI Video Check",
    title="AI Video Check",
    description="Check whether a video was generated by AI (Sora, Veo, Kling and others).",
    instructions=(
        "Use these tools to check whether a video was generated by AI. Pass a public link "
        "to check_video. Report the result with its caveats; never present a score as proof. "
        "Each check spends credits from the user's AI Video Check account (one credit per "
        "started minute of video)."
    ),
    website_url=SITE,
    version="1.0.0",
)


class ToolFailure(ToolError):
    """A message meant for the assistant (and the user), not a stack trace.

    Must be a ToolError: the SDK passes a ToolError's text to the client as is,
    but replaces the text of any other exception with a generic message, so the
    user would read "unexpected error" instead of "not enough credits".
    """


def _api_key(ctx: Optional[Context]) -> str:
    headers = (ctx.headers if ctx is not None else None) or {}
    auth = headers.get("authorization") or headers.get("Authorization") or ""
    if auth.lower().startswith("bearer "):
        return auth[7:].strip()
    if _MODE["stdio"]:
        key = os.getenv("AVC_API_KEY", "").strip()
        if key:
            return key
    raise ToolFailure(
        "No AI Video Check API key. Create one on your account page "
        f"({SITE}/en/dashboard/account) and configure this server with it: "
        "the `Authorization: Bearer avc_live_…` header for the remote server, "
        "or the AVC_API_KEY environment variable for the local one."
    )


def _error_text(r: httpx.Response) -> str:
    try:
        err = r.json().get("error") or {}
    except Exception:
        err = {}
    code, message = err.get("code", ""), err.get("message") or f"HTTP {r.status_code}"
    if code == "invalid_api_key":
        return f"The API key was rejected ({message}). Check it on {SITE}/en/dashboard/account."
    if code == "insufficient_credits":
        need, have = err.get("required"), err.get("balance")
        tail = f" This video needs {need} credit(s); the balance is {have}." if need is not None else ""
        return f"Not enough credits.{tail} Credits can be bought at {SITE}/en/tariffs."
    if code in ("rate_limited", "too_many_in_flight"):
        wait = r.headers.get("Retry-After")
        return f"{message}" + (f" Try again in {wait} s." if wait else "")
    return f"{message}" + (f" (code: {code})" if code else "")


async def _request(ctx: Optional[Context], method: str, path: str, **kw: Any) -> dict:
    key = _api_key(ctx)
    headers = {"Authorization": f"Bearer {key}", "User-Agent": USER_AGENT,
               **kw.pop("headers", {})}
    if FORWARD_CLIENT_IP and ctx is not None:
        ip = (ctx.headers or {}).get("x-real-ip")
        if ip:
            headers["X-Real-IP"] = ip
    try:
        async with httpx.AsyncClient(base_url=API_BASE, timeout=httpx.Timeout(60.0, connect=10.0)) as c:
            r = await c.request(method, path, headers=headers, **kw)
    except httpx.HTTPError:
        raise ToolFailure("AI Video Check could not be reached just now. Try again in a minute.")
    if r.status_code >= 400:
        raise ToolFailure(_error_text(r))
    return r.json()


def _pct(x: Any) -> str:
    # One decimal, like the website. Whole numbers turned 99.7 into "100%",
    # which an assistant reads as certainty - the one thing this text avoids.
    return "n/a" if x is None else f"{float(x):.1f}%"


def _format(body: dict) -> str:
    status, cid = body.get("status"), body.get("id")
    if status == "failed":
        err = body.get("error") or {}
        return (f"The check failed: {err.get('message') or err.get('code') or 'unknown error'} "
                f"The credits for it were returned. Check id: {cid}.")
    if status != "succeeded":
        prog = body.get("progress")
        where = f" ({prog * 100:.0f}% done)" if isinstance(prog, (int, float)) and status == "processing" else ""
        return (f"The check is still {status}{where}. Check id: {cid}. "
                "Call get_check with this id in a little while.")

    res = body.get("result") or {}
    lines = [
        f"Result: {VERDICT.get(res.get('verdict'), res.get('verdict'))} — "
        f"{_pct(res.get('probability'))} probability of AI generation.",
        f"Picture model: {_pct(res.get('video_probability'))}. "
        f"Sound model: {_pct(res.get('audio_probability'))}.",
    ]
    prov = res.get("provenance") or {}
    if prov.get("present"):
        who = prov.get("signer") or prov.get("claim_generator") or "an unnamed signer"
        ok = {True: "the signature verifies", False: "the signature does NOT verify"}.get(
            prov.get("verified"), "the signature could not be verified")
        says = "declares AI generation" if prov.get("declares_ai") else "does not declare AI generation"
        lines.append(f"Content Credentials (C2PA): signed by {who}; {ok}; the credential {says}.")
    meta = []
    if res.get("duration_s") is not None:
        meta.append(f"video length {float(res['duration_s']):.0f} s")
    meta.append(f"credits charged {body.get('credits_charged', '?')}")
    if res.get("model_version"):
        meta.append(f"model {res['model_version']}")
    meta.append(f"check id {cid}")
    lines.append("; ".join(meta).capitalize() + ".")
    lines.append(HOW_TO_READ)
    return "\n".join(lines)


async def _wait(ctx: Optional[Context], created: dict) -> str:
    cid = created.get("id")
    body = created
    loop = asyncio.get_running_loop()
    deadline = loop.time() + WAIT_S
    while body.get("status") in ("queued", "processing") and loop.time() < deadline:
        await asyncio.sleep(POLL_S)
        body = await _request(ctx, "GET", f"/v1/checks/{cid}")
        if ctx is not None and isinstance(body.get("progress"), (int, float)):
            try:
                await ctx.report_progress(float(body["progress"]), 1.0)
            except Exception:
                pass  # progress is a courtesy; a client that ignores it is fine
    return _format(body)



@server.tool(
    title="Check a video by link",
    annotations=ToolAnnotations(readOnlyHint=False, destructiveHint=False,
                                idempotentHint=False, openWorldHint=True),
)
async def check_video(url: str, ctx: Context) -> str:
    """Check whether the video at a public link (TikTok, Instagram, X, YouTube, Facebook
    or a direct file URL) was generated by AI. Spends credits: one per started minute of
    video. Waits up to about a minute; if the check is not done by then, returns its id
    for get_check."""
    created = await _request(ctx, "POST", "/v1/checks", json={"url": url},
                             headers={"Idempotency-Key": str(uuid.uuid4())})
    return await _wait(ctx, created)


@server.tool(
    title="Get a check result",
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=True),
)
async def get_check(check_id: str, ctx: Context) -> str:
    """Get the status or result of an earlier check by its id. Free. Results are kept
    for 24 hours."""
    return _format(await _request(ctx, "GET", f"/v1/checks/{check_id}"))


@server.tool(
    title="Credit balance",
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=True),
)
async def get_balance(ctx: Context) -> str:
    """Show how many AI Video Check credits the account has left and the limits of its key.
    Free."""
    acc = await _request(ctx, "GET", "/v1/account")
    lim = acc.get("limits") or {}
    return (f"Balance: {(acc.get('credits') or {}).get('balance')} credit(s). "
            f"One credit covers one started minute of video. "
            f"Limits: videos up to {int(lim.get('max_video_seconds', 600)) // 60} min and "
            f"{lim.get('max_upload_mb', MAX_FILE_MB)} MB; {lim.get('checks_in_flight', 5)} checks at once. "
            f"Buy credits at {SITE}/en/tariffs.")


VIDEO_SUFFIXES = {".mp4", ".m4v", ".mov", ".webm", ".mkv", ".avi", ".3gp", ".mpeg", ".mpg", ".ts", ".flv", ".wmv"}


def _looks_like_video(p: Path) -> bool:
    """check_file reads the user's own disk, so an instruction smuggled into a web page
    or a document could ask the assistant to "check" ~/.ssh/id_rsa and ship it to us.
    Only files that are named AND built like a video container ever leave the machine."""
    if p.suffix.lower() not in VIDEO_SUFFIXES:
        return False
    with p.open("rb") as fh:
        head = fh.read(189)
    return (head[4:8] == b"ftyp"                         # MP4, MOV, M4V, 3GP
            or head[:4] == bytes.fromhex("1a45dfa3")      # Matroska, WebM
            or (head[:4] == b"RIFF" and head[8:12] == b"AVI ")
            or head[:3] == b"FLV"
            or head[:4] in (bytes.fromhex("000001ba"), bytes.fromhex("000001b3"))  # MPEG-PS
            # MPEG-TS: sync byte at the start of two consecutive 188-byte packets.
            # One byte alone is just the letter "G", and .ts is also TypeScript.
            or (len(head) == 189 and head[0] == 0x47 and head[188] == 0x47)
            or head[:16] == bytes.fromhex("3026b2758e66cf11a6d900aa0062ce6c"))  # ASF / WMV


async def check_file(path: str, ctx: Context) -> str:
    """Check whether a video file on this computer was generated by AI. Uploading the
    original file gives a more reliable result than a link. Spends credits: one per
    started minute of video."""
    p = Path(path).expanduser()
    if not p.is_file():
        raise ToolFailure(f"No file at {p}.")
    if not _looks_like_video(p):
        raise ToolFailure(f"{p.name} does not look like a video file, so it was not sent.")
    size_mb = p.stat().st_size / (1024 * 1024)
    if size_mb > MAX_FILE_MB:
        raise ToolFailure(f"The file is {size_mb:.0f} MB; the limit is {MAX_FILE_MB} MB.")
    with p.open("rb") as fh:
        created = await _request(ctx, "POST", "/v1/checks",
                                 files={"file": (p.name, fh, "application/octet-stream")},
                                 headers={"Idempotency-Key": str(uuid.uuid4())})
    return await _wait(ctx, created)


def _http_app():
    # Behind nginx the Host header is the public name; SDK's DNS-rebinding
    # guard would otherwise accept only localhost and refuse every real call.
    hosts = [h.strip() for h in os.getenv("AVC_MCP_ALLOWED_HOSTS",
                                          "api.aivideocheck.net,127.0.0.1:*,localhost:*").split(",") if h.strip()]
    return server.streamable_http_app(
        streamable_http_path="/mcp",
        stateless_http=True,
        json_response=True,
        transport_security=TransportSecuritySettings(allowed_hosts=hosts, allowed_origins=[]),
    )


app = _http_app()


def main() -> None:
    """Local (stdio) entry point: `python avc_mcp.py` or the `aivideocheck-mcp` command."""
    _MODE["stdio"] = True
    server.tool(
        title="Check a video file",
        annotations=ToolAnnotations(readOnlyHint=False, destructiveHint=False,
                                    idempotentHint=False, openWorldHint=True),
    )(check_file)
    server.run("stdio")


if __name__ == "__main__":
    main()
